---
- name: Create "{{ dbname }}" DB
  hosts: master  #master... Master of puppets i`m pulling your strings...
  become: true
  become_user: postgres
  gather_facts: true
  vars_files:
    - vars/user_vars.yml

  tasks:

  - name: Create "{{ dbname }}" db
    community.postgresql.postgresql_db:
      name: "{{ dbname }}"
      encoding: 'UTF-8'
      lc_collate: 'ru_RU.UTF-8'
      lc_ctype: 'ru_RU.UTF-8'
      state: present

  - name: Create "{{ dbname }}" role for db
    community.postgresql.postgresql_user:
      db: "{{ dbname }}"
      user: "{{ dbuser }}"
      password: "{{ dbpassword }}"
      priv: ALL
      state: present

  - name: Copy file
    ansible.builtin.copy:
      src: ./init.sql #edit path to init.sql file
      dest: /var/lib/postgresql/init.sql #default DB path
      mode: '0666'

  - name: Importing "{{ dbname }}" db
    ansible.builtin.shell:
      psql "{{ dbname }}" < /var/lib/postgresql/init.sql

  - name: Grant usage of schema to "{{ dbname }}" role
    community.postgresql.postgresql_privs:
      database: "{{ dbname }}"
      state: present
      privs: USAGE
      type: schema
      roles: "{{ dbuser }}"
      objs: public

  - name: Grant table permissions for "{{ dbuser }}" role
    community.postgresql.postgresql_privs: 
      database: "{{ dbname }}"
      schema: public
      state: present
      privs: SELECT,INSERT,UPDATE
      type: table
      roles: "{{ dbuser }}"
      grant_option: no
      objs: ALL_IN_SCHEMA

  - name: Grant permissions for "{{ dbuser }}" role
    community.postgresql.postgresql_privs: 
      database: "{{ dbname }}"
      schema: public
      state: present
      privs: USAGE
      type: sequence
      roles: "{{ dbuser }}"
      grant_option: no
      objs: ALL_IN_SCHEMA
