# Default values for weather-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: ghcr.io/ldest/sre-course/api:c4f3862
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "s71-weather-app"

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: "student71"

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8083
  targetPort: 8083

ingress:
  enabled: true
  className: "nginx"
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: weather.student71.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: "100m"
    memory: "256Mi"
  requests:
    cpu: "50m"
    memory: "64Mi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
envmap:
  - name: "ASPNETCORE_URLS" 
    value: "http://*:8083"
  - name: "DOTNET_ENVIRONMENT"
    value: 'Production'
#    value: 'Development'
  - name: "CONNECTIONSTRINGS__PGCONNECTION"
    value: "server='0.0.0.0'; port='5000'; database='weather'; user id='admin'; password='password';"
uservars:
    probe:
      delay: "10"
      period: "10"
      timeout: "10"
      livepath: "/healthz/live"
      readpath: " /healthz/ready"
